bin/cake bake all alumno_materia
bin/cake bake all alumnos
bin/cake bake all carrera_materia
bin/cake bake all carreras
bin/cake bake all docente_materia
bin/cake bake all docentes
bin/cake bake all grupo_materia
bin/cake bake all grupos
bin/cake bake all horarios
bin/cake bake all materia_horario
bin/cake bake all materias
bin/cake bake all users
